type Query {
    book(id: Int!): Book
    books(author: String): [Book]
},
type Mutation {
    updateBookAuthor(id: Int!, author: String!): Book
}
type Book {
    id: Int
    title: String
    author: String
    description: String
}
